### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by lig** [erickzanardo/dashbook#24]
I'm going to submit a PR for the null safety support.

It is a common practice to keep such a code in a separate branch, i.e. `null-safety`, to be able to support the main release in legacy mode whilst the null safety compatible release could be released from its branch.

Please, prepare the branch for null safety support PR.

**Comment by lig** [comment]
`flutter_colorpicker` null safety PR: https://github.com/mchome/flutter_colorpicker/pull/36

**Comment by lig** [comment]
#28 allows releasing the null safety compatible pre-release package

**Comment by lig** [comment]
@erickzanardo as #28 is merged, could you please release a null safety compatible pre-release version of the package?

**Comment by erickzanardo-creditas** [comment]
> @erickzanardo as #28 is merged, could you please release a null safety compatible pre-release version of the package?

Done https://pub.dev/packages/dashbook/versions/0.1.0-nullsafety.0

**Comment by erickzanardo** [comment]
> @erickzanardo as #28 is merged, could you please release a null safety compatible pre-release version of the package?

Done https://pub.dev/packages/dashbook/versions/0.1.0-nullsafety.0

**Comment by lig** [comment]
Thanks! I think this issue could be closed now. Nothing to do here until the main branch changes or null safety goes out of beta.
