### ISSUE TITLE
Routing support

### ISSUE THREAD

**Issue by chimon2000** [erickzanardo/dashbook#32]
It would be nice if stories could be broken up by routes, so that a developer could provide links to specific stories in other resources (such as dart docs or design websites).  Currently, a user would just be directed to the initial page.

This could be automatically computed from the story name, or an additional `route` parameter could be added to the `storiesOf` function.

```dart
dashbook.storiesOf('RaisedButton') // Route automatically converted to some type url friendly case.

//or

dashbook.storiesOf('RaisedButton', route: 'raised-button') // Route explicitly defined. 
```

**Comment by erickzanardo** [comment]
Solved in #46, whenever running on web, a share button is now available which copies a link to your clipboard which then can be used as a permanent link to that chapter.
