### ISSUE TITLE
Large property fields do not render correctly

### ISSUE THREAD

**Issue by chimon2000** [erickzanardo/dashbook#38]
Looking at the 2nd property of the following example.

<img src="https://user-images.githubusercontent.com/6907797/108955499-47d21e00-763c-11eb-84b8-d6199690f490.png" width=300>

I have changed the list value to include a long text value to show that it does not render correctly.  

A few options:

1. DropdownMenuItem Text uses overflow ellipsis
2. Input field rendered on a new line below label
3. DropdownMenuItem Text is wrapped in a FittedBox causing the text to shrink.

**Comment by erickzanardo** [comment]
@chimon2000 We have just released dashbook 0.0.13 that includes a change regarding that. It wraps the DropdownMenuItem, so you can see its full label, but the layout is not supposed to be broken. Could you take a look please?

**Comment by erickzanardo** [comment]
Closing due inactivity, if this issue is still happening on newer versions, please, let me know and I will re open this!
