### ISSUE TITLE
Add navigatorKey to Dashbook

### ISSUE THREAD

**Issue by aqwert** [erickzanardo/dashbook#41]
Currently I use navigator key in my app to do navigation. It would be great if the navigatorKey was exposed through Dashbook so it can be set onto the MaterialApp.

```
Dashbook(navigatorKey: globalNavKey, ...)
```

**Comment by erickzanardo** [comment]
Just added this new parameter on Dashbook `0.1.0`.

**Comment by aqwert** [comment]
Thanks
