### ISSUE TITLE
Dynamic Properties

### ISSUE THREAD

**Issue by jeffscaturro-aka** [erickzanardo/dashbook#47]
It would be nice to have dynamic properties that become visible or hidden based on another property.

For instance, you can have a type property that drives subsequent properties that are visible, such as an additional label only present if that type were selected.

**Comment by erickzanardo** [comment]
Hey, thanks for the suggestion.

I think I got the idea but I am not 100% sure.

Could elaborate more? Would be cool if you could put an example of what you would expect the API would look like.

**Comment by jeffscaturro-aka** [comment]
Sure!

We add options to the `DashbookContext` and store them in a map of `properties`: https://github.com/erickzanardo/dashbook/blob/f2581ce298242a07302482b4eccb8045197ce2a4/lib/src/story.dart#L26-L27

It would be valuable to add some logic conditional on another property's key/value pair. Here is some high-level pseudocode that I'm sure would bring in some edge-cases or handling that needs to be accounted for somewhere else, but it provides the gist of the ask here.

```dart
class DashbookContext {
  /// Contain the current BoxConstraints of the area available for the Chapter
  BoxConstraints? constraints;
  Map<String, Property> properties = {};

  String textProperty(
    String name,
    String defaultValue, {
    String presentOnKey,
    T presentOnKeyValue,
  }) {
    if (properties.containsKey(presentOnKey) &&
        properties[presentOnKey]!.getValue() == presentOnKeyValue) {
      if (properties.containsKey(name)) {
        return properties[name]!.getValue();
      } else {
        final property = Property<String>(name, defaultValue);
        properties[name] = property;

        return property.getValue();
      }
    } else {
      properties.remove(name);
    }
  }
```

This would then enable consumers to do something like:

```dart
...
text: dashbookContext.textProperty(
    'Error Text',
    'Oops, something went wrong!',
    presentOnKey: 'state',
    presentOnKeyValue: SomeEnumDef.errorState,
  ),
...
```

Where the user would only see the "Error Text" property (on the Properties tab) if the Property "state" is `SomeEnumDef.errorState`.

I'm not saying this approach is the best way to accomplish this as I haven't looked too in-depth into the source code, but hopefully it provides more context and an example of the intent behind this ask.

Let me know if not.

**Comment by erickzanardo** [comment]
Got it @jeffscaturro-aka, thanks for the further explanation, I made some adaptations to your suggestion and just submitted #49
