### ISSUE TITLE
Properties list do not render correctly

### ISSUE THREAD

**Issue by emersonsiega** [erickzanardo/dashbook#54]
I think there's a bug with properties list..

I'm using dual theme option and the properties list appears just if I change the theme.

Changing between components have the same issue. Always need to change theme once.

![](https://media.giphy.com/media/LO57cQrK263CUISdKM/giphy.gif)

**Comment by erickzanardo** [comment]
Interesting, does that happens only with listProperties?

**Comment by emersonsiega** [comment]
Yeah..

And I've just realized that only happens on the first I access the component...

1. Access Component A 
2. Toggle theme (properties list appears)
3. Access Component B (properties are hidden)
4. Access Component A, properties list are visible

**Comment by erickzanardo** [comment]
@emersonsiega I am not having luck trying to reproduce this bug.

I even wrote a small widget test that simulates this scenario and was suppose to fail: https://github.com/erickzanardo/dashbook/blob/main/test/properties/list_property_test.dart#L26

I wonder if you could share with me a minimal reproducible code where this bug happens? It would be very helpful.

**Comment by emersonsiega** [comment]
I was trying to create a simple project to reproduce this issue, then I realized that the problem is with the structure that I've created to work with a custom decorator... 

I'll close this issue.. Sorry for that...

**Comment by erickzanardo** [comment]
No problem! What matters is that we figured out the issue. Thanks for reporting back
